#!/usr/bin/env node
/**
 * opencode-team-runtime P6 memory runner
 *
 * Advisory-only memory, failure-pattern tracking, route-quality scoring,
 * and prompt/skill improvement suggestions. No third-party dependencies.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const VERSION = "0.8.0-p6";
const TEAM = [".opencode", "team"];

function now() { return new Date().toISOString(); }
function day() { return now().slice(0, 10); }
function id(prefix = "mem") { return `${prefix}-${crypto.randomBytes(4).toString("hex")}`; }
function clone(x) { return JSON.parse(JSON.stringify(x)); }
function teamPath(project, ...parts) { return path.join(project, ...TEAM, ...parts); }
function memPath(project, ...parts) { return teamPath(project, "memory", ...parts); }
function routerPath(project, ...parts) { return teamPath(project, "router", ...parts); }
function rel(project, file) { return path.relative(project, file); }

function readText(file, fallback = "") {
  try { return fs.existsSync(file) ? fs.readFileSync(file, "utf8") : fallback; } catch { return fallback; }
}
function readJson(file, fallback = {}) {
  try {
    if (!fs.existsSync(file)) return clone(fallback);
    const raw = fs.readFileSync(file, "utf8").trim();
    return raw ? JSON.parse(raw) : clone(fallback);
  } catch (err) {
    throw new Error(`Failed to read JSON ${file}: ${err.message}`);
  }
}
function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n");
}
function readJsonl(file) {
  return readText(file, "").split(/\r?\n/).filter(Boolean).map(line => {
    try { return JSON.parse(line); } catch { return null; }
  }).filter(Boolean);
}
function appendJsonl(file, obj) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.appendFileSync(file, JSON.stringify(obj) + "\n");
}
function appendEvidence(project, type, status, body) {
  const file = teamPath(project, "evidence.md");
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.appendFileSync(file, `\n## ${now()} — ${type} — ${status}\n\n${String(body || "").trim()}\n`);
}

function defaultConfig() {
  return {
    version: VERSION,
    mode: "advisory-only",
    autoApply: false,
    protectedPaths: [".opencode/scripts/", ".opencode/plugins/", ".opencode/mcp/"],
    allowedWritePaths: [".opencode/team/memory/", ".opencode/agents/", ".opencode/skills/"],
    minimumEvidenceForSuggestion: 2,
    routeQuality: { successWeight: 1, failureWeight: -1, premiumCostPenalty: -0.25, repeatFailurePenalty: -0.5 }
  };
}
function defaultScorecard() {
  return { version: VERSION, models: {}, agents: {}, pairs: {}, patterns: {} };
}
function defaultSuggestions() { return { version: VERSION, suggestions: [] }; }

export function ensure(project) {
  fs.mkdirSync(memPath(project, "approvals"), { recursive: true });
  fs.mkdirSync(memPath(project, "packs"), { recursive: true });
  const files = {
    config: memPath(project, "config.json"),
    events: memPath(project, "events.jsonl"),
    lessons: memPath(project, "lessons.jsonl"),
    scorecard: memPath(project, "model-scorecard.json"),
    suggestions: memPath(project, "suggestions.json"),
    promptNotes: memPath(project, "prompt-notes.md")
  };
  if (!fs.existsSync(files.config)) writeJson(files.config, defaultConfig());
  if (!fs.existsSync(files.events)) fs.writeFileSync(files.events, "");
  if (!fs.existsSync(files.lessons)) fs.writeFileSync(files.lessons, "");
  if (!fs.existsSync(files.scorecard)) writeJson(files.scorecard, defaultScorecard());
  if (!fs.existsSync(files.suggestions)) writeJson(files.suggestions, defaultSuggestions());
  if (!fs.existsSync(files.promptNotes)) fs.writeFileSync(files.promptNotes, "# Team Runtime Prompt Notes\n\nAdvisory-only notes generated by P6 memory.\n");
  return files;
}

function normalizeOutcome(value) {
  const v = String(value || "").toLowerCase();
  if (["pass", "passed", "success", "succeeded", "ok", "done"].includes(v)) return "success";
  if (["fail", "failed", "failure", "error", "blocked", "regression"].includes(v)) return "failure";
  if (["warn", "warning", "mixed", "partial"].includes(v)) return "mixed";
  return "unknown";
}
function normalizeTags(tags) {
  if (Array.isArray(tags)) return tags.map(String).map(s => s.trim()).filter(Boolean);
  return String(tags || "").split(/[;,]/).map(s => s.trim()).filter(Boolean);
}
function bucketText(text = "") {
  const t = String(text).toLowerCase();
  const buckets = [];
  const patterns = [
    ["premature_done", /(claim|claimed|declare|declared|done|complete|完成|声称|宣称).{0,60}(missing|not implemented|未实现|没实现|incomplete|未完成)/i],
    ["test_failure", /(test|pytest|npm test|pnpm test|cargo test|失败|failed|assertion|regression)/i],
    ["browser_failure", /(browser|screenshot|console|network|dom|selector|captcha|2fa|登录|网页|浏览器)/i],
    ["context_noise", /(context|compact|handoff|noise|上下文|压缩|轮换|handoff)/i],
    ["research_unsupported", /(unsupported|no evidence|without evidence|evidence|citation|source_id|source|claim-evidence|无证据|引用|来源)/i],
    ["permission_safety", /(permission|secret|env|api key|token|password|危险|权限|密钥)/i],
    ["dependency_install", /(install|dependency|package|npm|pip|cargo|依赖|安装)/i]
  ];
  for (const [name, rx] of patterns) if (rx.test(t)) buckets.push(name);
  return buckets.length ? buckets : ["general"];
}

export function record(project, input = {}) {
  ensure(project);
  const outcome = normalizeOutcome(input.outcome || input.status || input.kind);
  const text = String(input.text || input.reason || input.note || "").trim();
  const event = {
    id: input.id || id("evt"),
    time: now(),
    day: day(),
    kind: input.kind || (outcome === "success" ? "success" : outcome === "failure" ? "failure" : "note"),
    outcome,
    agent: input.agent || input.role || "",
    model: input.model || "",
    task: input.task || "",
    severity: input.severity || (outcome === "failure" ? "medium" : "info"),
    tags: Array.from(new Set([...normalizeTags(input.tags), ...bucketText(text)])),
    text,
    source: input.source || "manual"
  };
  appendJsonl(memPath(project, "events.jsonl"), event);
  if (input.kind === "lesson" || input.lesson) appendJsonl(memPath(project, "lessons.jsonl"), event);
  appendEvidence(project, "memory", event.outcome, `- id: ${event.id}\n- agent: ${event.agent || "n/a"}\n- model: ${event.model || "n/a"}\n- tags: ${event.tags.join(", ") || "n/a"}\n\n${event.text || "(no text)"}`);
  return event;
}

function incStats(obj, key, event) {
  if (!key) return;
  if (!obj[key]) obj[key] = { total: 0, success: 0, failure: 0, mixed: 0, unknown: 0, score: 0, tags: {}, lastSeen: "" };
  const s = obj[key];
  s.total += 1;
  s[event.outcome] = (s[event.outcome] || 0) + 1;
  s.lastSeen = event.time;
  for (const tag of event.tags || []) s.tags[tag] = (s.tags[tag] || 0) + 1;
}
function scoreFor(stats) {
  if (!stats || !stats.total) return 0;
  const raw = (stats.success || 0) - (stats.failure || 0) - 0.25 * (stats.mixed || 0);
  return Number((raw / Math.max(1, stats.total)).toFixed(3));
}

export function analyze(project, opts = {}) {
  ensure(project);
  const events = readJsonl(memPath(project, "events.jsonl"));
  const routerDecisions = readJsonl(routerPath(project, "decisions.jsonl"));
  const scorecard = defaultScorecard();

  for (const event of events) {
    incStats(scorecard.models, event.model, event);
    incStats(scorecard.agents, event.agent, event);
    incStats(scorecard.pairs, event.agent && event.model ? `${event.agent}::${event.model}` : "", event);
    for (const tag of event.tags || []) {
      if (!scorecard.patterns[tag]) scorecard.patterns[tag] = { total: 0, success: 0, failure: 0, mixed: 0, unknown: 0, examples: [] };
      const p = scorecard.patterns[tag];
      p.total += 1;
      p[event.outcome] = (p[event.outcome] || 0) + 1;
      if (p.examples.length < 5 && event.text) p.examples.push({ id: event.id, time: event.time, agent: event.agent, model: event.model, text: event.text.slice(0, 280) });
    }
  }
  for (const table of [scorecard.models, scorecard.agents, scorecard.pairs, scorecard.patterns]) {
    for (const value of Object.values(table)) value.score = scoreFor(value);
  }
  scorecard.router = { decisions: routerDecisions.length, recent: routerDecisions.slice(-10) };
  scorecard.generatedAt = now();
  writeJson(memPath(project, "model-scorecard.json"), scorecard);
  return scorecard;
}

function topTags(stats, n = 5) {
  return Object.entries(stats?.tags || {}).sort((a, b) => b[1] - a[1]).slice(0, n).map(([k, v]) => `${k}:${v}`).join(", ");
}
function addSuggestion(list, sug) {
  if (!sug.id) sug.id = id("sug");
  sug.time = sug.time || now();
  sug.status = sug.status || "proposed";
  list.push(sug);
}

export function generateSuggestions(project, opts = {}) {
  ensure(project);
  const config = readJson(memPath(project, "config.json"), defaultConfig());
  const scorecard = analyze(project, opts);
  const existing = readJson(memPath(project, "suggestions.json"), defaultSuggestions());
  const suggestions = [];
  const minEvidence = Number(config.minimumEvidenceForSuggestion || 2);

  for (const [pair, stats] of Object.entries(scorecard.pairs || {})) {
    if (stats.total >= minEvidence && (stats.failure || 0) >= minEvidence && stats.score < 0) {
      const [agent, model] = pair.split("::");
      addSuggestion(suggestions, {
        type: "route",
        title: `Consider rerouting ${agent} away from ${model} for repeated failures`,
        evidenceCount: stats.total,
        target: { agent, model },
        rationale: `Score ${stats.score}; failures ${stats.failure}/${stats.total}; common tags: ${topTags(stats)}.` ,
        recommendation: `Use router fallback/escalation for ${agent} when tags match ${Object.keys(stats.tags || {}).slice(0, 3).join(", ") || "this failure pattern"}.`,
        safeToAutoApply: false
      });
    }
  }

  for (const [tag, stats] of Object.entries(scorecard.patterns || {})) {
    if ((stats.failure || 0) >= minEvidence) {
      if (tag === "premature_done") addSuggestion(suggestions, {
        type: "prompt",
        title: "Strengthen done-gate wording for premature completion",
        evidenceCount: stats.failure,
        target: { files: [".opencode/agents/minimax-coder.md", ".opencode/agents/reviewer.md"] },
        rationale: `Detected ${stats.failure} premature-completion related failure events.`,
        recommendation: "Require changed-file list, exact tests run, output paths, and explicit TODO status before any agent can claim completion.",
        safeToAutoApply: false
      });
      else if (tag === "browser_failure") addSuggestion(suggestions, {
        type: "browser",
        title: "Require browser evidence for UI-related claims",
        evidenceCount: stats.failure,
        target: { files: [".opencode/agents/browser-tester.md", ".opencode/agents/reviewer.md"] },
        rationale: `Detected ${stats.failure} browser/UI related failure events.`,
        recommendation: "For UI tasks, require ScreenDigest, marked screenshot, console/network clean result, and at least one browser assertion.",
        safeToAutoApply: false
      });
      else if (tag === "research_unsupported") addSuggestion(suggestions, {
        type: "research",
        title: "Tighten claim-evidence validation before research reports",
        evidenceCount: stats.failure,
        target: { files: [".opencode/agents/research-scout.md", ".opencode/agents/research-reviewer.md"] },
        rationale: `Detected ${stats.failure} unsupported claim/evidence failures.`,
        recommendation: "Reject any report paragraph whose key claim lacks a source_id#chunk_id evidence reference and validation status.",
        safeToAutoApply: false
      });
      else if (tag === "context_noise") addSuggestion(suggestions, {
        type: "context",
        title: "Rotate earlier or generate smaller context packs",
        evidenceCount: stats.failure,
        target: { files: [".opencode/team/runtime.config.json", ".opencode/agents/handoff-writer.md"] },
        rationale: `Detected ${stats.failure} context/compaction/rotation related failures.`,
        recommendation: "Generate a fresh context pack before review/handoff and reduce weak-model context packs to the minimum files/tests/evidence for one task.",
        safeToAutoApply: false
      });
    }
  }

  const merged = [...(existing.suggestions || []).filter(s => s.status && s.status !== "proposed"), ...suggestions];
  const out = { version: VERSION, generatedAt: now(), mode: config.mode || "advisory-only", suggestions: merged };
  writeJson(memPath(project, "suggestions.json"), out);
  writePromptNotes(project, out.suggestions);
  return out;
}

export function writePromptNotes(project, suggestions = null) {
  ensure(project);
  const data = suggestions ? { suggestions } : readJson(memPath(project, "suggestions.json"), defaultSuggestions());
  const proposed = (data.suggestions || []).filter(s => s.status === "proposed");
  const lines = [
    "# Team Runtime Prompt Notes",
    "",
    `Generated: ${now()}`,
    "",
    "These notes are advisory-only. Do not auto-apply them to core runtime files without review.",
    "",
    "## Active Suggestions",
    ""
  ];
  if (!proposed.length) lines.push("No active suggestions.");
  for (const s of proposed) {
    lines.push(`### ${s.title}`);
    lines.push(`- id: ${s.id}`);
    lines.push(`- type: ${s.type}`);
    lines.push(`- evidence: ${s.evidenceCount || 0}`);
    if (s.target) lines.push(`- target: ${JSON.stringify(s.target)}`);
    lines.push(`- rationale: ${s.rationale || ""}`);
    lines.push(`- recommendation: ${s.recommendation || ""}`);
    lines.push("");
  }
  fs.writeFileSync(memPath(project, "prompt-notes.md"), lines.join("\n") + "\n");
  return memPath(project, "prompt-notes.md");
}

function parseEvidenceSections(project) {
  const text = readText(teamPath(project, "evidence.md"));
  const chunks = text.split(/\n##\s+/).map((s, idx) => idx === 0 ? s : "## " + s).filter(s => s.trim());
  const events = [];
  for (const chunk of chunks.slice(-200)) {
    if (/—\s*memory\s*—/i.test(chunk) || /—\s*memory-review\s*—/i.test(chunk)) continue;
    const low = chunk.toLowerCase();
    const failure = /(fail|failed|error|blocked|unsupported|missing|not implemented|失败|未实现|未完成)/i.test(chunk);
    const success = /(pass|passed|success|supported|clean|通过|成功)/i.test(chunk) && !failure;
    if (!failure && !success) continue;
    const agent = (chunk.match(/agent:\s*([^\n]+)/i)?.[1] || "").trim();
    const model = (chunk.match(/model:\s*([^\n]+)/i)?.[1] || "").trim();
    events.push({ kind: failure ? "failure" : "success", outcome: failure ? "failure" : "success", agent, model, text: chunk.slice(0, 2000), source: "evidence.md" });
  }
  return events;
}
function parseRouterDecisions(project) {
  const decisions = readJsonl(routerPath(project, "decisions.jsonl"));
  const events = [];
  for (const d of decisions.slice(-300)) {
    const reason = d.reason || d.input?.reason || d.decision?.reason || "";
    const model = d.model || d.alias || d.decision?.modelAlias || d.decision?.alias || "";
    const agent = d.role || d.input?.role || d.agent || "";
    const warned = JSON.stringify(d).toLowerCase().includes("warning") || JSON.stringify(d).toLowerCase().includes("escalat");
    if (warned) events.push({ kind: "route", outcome: "mixed", agent, model, text: `Router warning/escalation: ${reason}\n${JSON.stringify(d).slice(0, 1200)}`, source: "router/decisions.jsonl" });
  }
  return events;
}
function parseTaskDag(project) {
  const dag = readJson(teamPath(project, "task-dag.json"), { tasks: [] });
  const events = [];
  for (const t of (dag.tasks || []).slice(-200)) {
    const st = String(t.status || "").toLowerCase();
    if (["failed", "blocked", "rejected"].includes(st)) events.push({ kind: "failure", outcome: "failure", agent: t.agent || "", model: t.model || "", task: t.id || "", text: `${t.title || t.id}: ${t.notes || t.result || t.error || st}`, source: "task-dag.json" });
    else if (["done", "passed", "accepted"].includes(st)) events.push({ kind: "success", outcome: "success", agent: t.agent || "", model: t.model || "", task: t.id || "", text: `${t.title || t.id}: ${t.notes || t.result || st}`, source: "task-dag.json" });
  }
  return events;
}

export function learn(project, opts = {}) {
  ensure(project);
  const sources = opts.from || opts.source || "all";
  const events = [];
  if (sources === "all" || sources.includes("evidence")) events.push(...parseEvidenceSections(project));
  if (sources === "all" || sources.includes("router")) events.push(...parseRouterDecisions(project));
  if (sources === "all" || sources.includes("task")) events.push(...parseTaskDag(project));
  const recorded = [];
  for (const e of events) recorded.push(record(project, e));
  const scorecard = analyze(project);
  const suggestions = generateSuggestions(project);
  return { recorded: recorded.length, scorecardPath: rel(project, memPath(project, "model-scorecard.json")), suggestionsPath: rel(project, memPath(project, "suggestions.json")), suggestions: suggestions.suggestions.length };
}

export function approve(project, suggestionId, decision = "approved", note = "") {
  ensure(project);
  const file = memPath(project, "suggestions.json");
  const data = readJson(file, defaultSuggestions());
  const target = (data.suggestions || []).find(s => s.id === suggestionId);
  if (!target) throw new Error(`Suggestion not found: ${suggestionId}`);
  target.status = decision;
  target.reviewedAt = now();
  target.reviewNote = note || "";
  writeJson(file, data);
  writeJson(memPath(project, "approvals", `${suggestionId}.json`), target);
  writePromptNotes(project, data.suggestions);
  appendEvidence(project, "memory-review", decision, `Suggestion ${suggestionId}: ${target.title}\n${note || ""}`);
  return target;
}

export function exportPack(project, query = "", opts = {}) {
  ensure(project);
  const scorecard = readJson(memPath(project, "model-scorecard.json"), defaultScorecard());
  const suggestions = readJson(memPath(project, "suggestions.json"), defaultSuggestions());
  const lessons = readJsonl(memPath(project, "lessons.jsonl")).slice(-20);
  const events = readJsonl(memPath(project, "events.jsonl")).slice(-50);
  const maxChars = Number(opts.maxChars || 16000);
  const lines = [
    "# Memory Pack",
    "",
    `Generated: ${now()}`,
    query ? `Query: ${query}` : "Query: general",
    "",
    "## Model Scorecard",
    "",
    "### Models",
  ];
  for (const [model, stats] of Object.entries(scorecard.models || {}).sort((a, b) => (a[1].score || 0) - (b[1].score || 0))) {
    lines.push(`- ${model}: score=${stats.score}, total=${stats.total}, success=${stats.success || 0}, failure=${stats.failure || 0}, tags=${topTags(stats)}`);
  }
  lines.push("", "### Agent/Model Pairs");
  for (const [pair, stats] of Object.entries(scorecard.pairs || {}).sort((a, b) => (a[1].score || 0) - (b[1].score || 0)).slice(0, 20)) {
    lines.push(`- ${pair}: score=${stats.score}, total=${stats.total}, failures=${stats.failure || 0}, tags=${topTags(stats)}`);
  }
  lines.push("", "## Active Suggestions");
  for (const s of (suggestions.suggestions || []).filter(x => x.status === "proposed").slice(0, 20)) {
    lines.push(`- ${s.id} [${s.type}] ${s.title}: ${s.recommendation}`);
  }
  lines.push("", "## Recent Lessons");
  for (const e of lessons) lines.push(`- ${e.time} ${e.agent || ""}/${e.model || ""}: ${e.text}`.slice(0, 500));
  lines.push("", "## Recent Events");
  for (const e of events) lines.push(`- ${e.time} ${e.outcome} ${e.agent || ""}/${e.model || ""} ${e.tags?.join(",") || ""}: ${e.text}`.slice(0, 500));
  let text = lines.join("\n");
  if (text.length > maxChars) text = text.slice(0, maxChars) + "\n\n[truncated]\n";
  const out = memPath(project, "packs", `memory-pack-${Date.now()}.md`);
  fs.writeFileSync(out, text + "\n");
  fs.writeFileSync(memPath(project, "current-pack.md"), text + "\n");
  return { path: rel(project, out), current: rel(project, memPath(project, "current-pack.md")), text };
}

export function status(project) {
  ensure(project);
  const events = readJsonl(memPath(project, "events.jsonl"));
  const suggestions = readJson(memPath(project, "suggestions.json"), defaultSuggestions());
  const scorecard = readJson(memPath(project, "model-scorecard.json"), defaultScorecard());
  return {
    version: VERSION,
    project,
    mode: readJson(memPath(project, "config.json"), defaultConfig()).mode,
    events: events.length,
    lessons: readJsonl(memPath(project, "lessons.jsonl")).length,
    suggestions: (suggestions.suggestions || []).length,
    proposedSuggestions: (suggestions.suggestions || []).filter(s => s.status === "proposed").length,
    modelsTracked: Object.keys(scorecard.models || {}).length,
    agentsTracked: Object.keys(scorecard.agents || {}).length,
    files: {
      events: rel(project, memPath(project, "events.jsonl")),
      scorecard: rel(project, memPath(project, "model-scorecard.json")),
      suggestions: rel(project, memPath(project, "suggestions.json")),
      promptNotes: rel(project, memPath(project, "prompt-notes.md"))
    }
  };
}

function parseArgs(argv) {
  const args = [...argv];
  const opts = { command: args.shift() || "help", project: process.cwd(), json: false, kind: "note", outcome: "", agent: "", model: "", task: "", severity: "", tags: [], text: "", source: "manual", from: "all", id: "", note: "", query: "", maxChars: 16000, _: [] };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (["--project", "--dir", "-C"].includes(a)) opts.project = path.resolve(args[++i]);
    else if (a === "--json") opts.json = true;
    else if (a === "--kind") opts.kind = args[++i];
    else if (["--outcome", "--status"].includes(a)) opts.outcome = args[++i];
    else if (a === "--agent" || a === "--role") opts.agent = args[++i];
    else if (a === "--model") opts.model = args[++i];
    else if (a === "--task") opts.task = args[++i];
    else if (a === "--severity") opts.severity = args[++i];
    else if (a === "--tags") opts.tags = args[++i];
    else if (["--text", "--reason"].includes(a)) opts.text = args[++i];
    else if (a === "--source") opts.source = args[++i];
    else if (a === "--from") opts.from = args[++i];
    else if (a === "--id") opts.id = args[++i];
    else if (a === "--note") opts.note = args[++i];
    else if (a === "--query") opts.query = args[++i];
    else if (a === "--max-chars") opts.maxChars = Number(args[++i]);
    else opts._.push(a);
  }
  if (!opts.text && opts._.length && opts.command === "record") opts.text = opts._.join(" ");
  if (!opts.query && opts._.length && opts.command === "pack") opts.query = opts._.join(" ");
  if (!opts.id && opts._.length && ["approve", "reject"].includes(opts.command)) opts.id = opts._[0];
  return opts;
}
function print(value, json = false) {
  if (json || typeof value !== "string") console.log(JSON.stringify(value, null, 2));
  else console.log(value);
}
function help() {
  console.log(`opencode-team-runtime memory ${VERSION}

Usage:
  opencode-memory doctor [--project DIR]
  opencode-memory status [--json]
  opencode-memory record --kind failure|success|lesson|note --agent AGENT --model MODEL --text TEXT [--tags a,b]
  opencode-memory learn [--from all|evidence|router|task]
  opencode-memory analyze [--json]
  opencode-memory suggestions [--json]
  opencode-memory pack "query" [--max-chars N]
  opencode-memory approve SUGGESTION_ID [--note TEXT]
  opencode-memory reject SUGGESTION_ID [--note TEXT]

Safety:
  P6 is advisory-only by default. It writes suggestions and prompt notes, not runtime code.
`);
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  const project = path.resolve(opts.project);
  ensure(project);
  if (opts.command === "help" || opts.command === "--help" || opts.command === "-h") return help();
  if (opts.command === "doctor") {
    const s = status(project);
    console.log(`P6 memory OK: ${s.files.events}`);
    console.log(`Mode: ${s.mode}; events: ${s.events}; suggestions: ${s.suggestions}`);
    return;
  }
  if (opts.command === "status") return print(status(project), opts.json);
  if (opts.command === "record") return print(record(project, opts), opts.json);
  if (opts.command === "learn") return print(learn(project, opts), opts.json);
  if (opts.command === "analyze") return print(analyze(project, opts), opts.json);
  if (opts.command === "suggestions") return print(generateSuggestions(project, opts), opts.json);
  if (opts.command === "pack") return print(exportPack(project, opts.query, opts), opts.json);
  if (opts.command === "approve") return print(approve(project, opts.id, "approved", opts.note), opts.json);
  if (opts.command === "reject") return print(approve(project, opts.id, "rejected", opts.note), opts.json);
  throw new Error(`Unknown command: ${opts.command}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(err => { console.error(`memory-runner error: ${err.message}`); process.exit(1); });
}
